/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiServersRouteImport } from './routes/api/servers'
import { Route as ApiReportsRouteImport } from './routes/api/reports'
import { Route as ApiIncidentsRouteImport } from './routes/api/incidents'
import { Route as ApiEventsRouteImport } from './routes/api/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServersRoute = ApiServersRouteImport.update({
  id: '/api/servers',
  path: '/api/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsRoute = ApiIncidentsRouteImport.update({
  id: '/api/incidents',
  path: '/api/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/servers': typeof ApiServersRoute
  '/api/status': typeof ApiStatusRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/servers': typeof ApiServersRoute
  '/api/status': typeof ApiStatusRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRoute
  '/api/incidents': typeof ApiIncidentsRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/servers': typeof ApiServersRoute
  '/api/status': typeof ApiStatusRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/events'
    | '/api/incidents'
    | '/api/reports'
    | '/api/servers'
    | '/api/status'
    | '/api/subscribe'
    | '/api/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/events'
    | '/api/incidents'
    | '/api/reports'
    | '/api/servers'
    | '/api/status'
    | '/api/subscribe'
    | '/api/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/api/events'
    | '/api/incidents'
    | '/api/reports'
    | '/api/servers'
    | '/api/status'
    | '/api/subscribe'
    | '/api/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiIncidentsRoute: typeof ApiIncidentsRoute
  ApiReportsRoute: typeof ApiReportsRoute
  ApiServersRoute: typeof ApiServersRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/servers': {
      id: '/api/servers'
      path: '/api/servers'
      fullPath: '/api/servers'
      preLoaderRoute: typeof ApiServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents': {
      id: '/api/incidents'
      path: '/api/incidents'
      fullPath: '/api/incidents'
      preLoaderRoute: typeof ApiIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiIncidentsRoute: ApiIncidentsRoute,
  ApiReportsRoute: ApiReportsRoute,
  ApiServersRoute: ApiServersRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
